// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzcxvoirhfbskzxmmqkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Y3h2b2lyaGZic2t6eG1tcWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjMxNTYsImV4cCI6MjA2MDc5OTE1Nn0.1rlirK35-5u3QZprbg7x_t1aWLxlcQpCJIQNGkHcg3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);